src/main/java/org/apache/doris/kafka/connector/writer/LabelGenerator.java, src/main/java/org/apache/doris/kafka/connector/writer/StreamLoadWriter.java
if kafka topic contained dot characters, which caused the stream load label verification to fail
=> [fix]Fixed the problem that the kafka topic contained dot characters

src/main/java/org/apache/doris/kafka/connector/cfg/DorisOptions.java, src/main/java/org/apache/doris/kafka/connector/cfg/DorisSinkConnectorConfig.java, src/main/java/org/apache/doris/kafka/connector/converter/ConverterMode.java, src/main/java/org/apache/doris/kafka/connector/converter/RecordService.java, src/main/java/org/apache/doris/kafka/connector/writer/DorisWriter.java, src/test/java/org/apache/doris/kafka/connector/converter/TestRecordService.java
When using debezium as kafka's upstream data source to synchronize data to doris, you need to configure ```converter.mode:debezium_ingestion```.
```converter.mode``` contains two conversion modes:
```normal``` mode: synchronize data directly from kafka to doris normally, this is also the default mode.
```debezium_ingestion``` mode: the upstream data source of kafka is debezium.
=> [fix]Fix using debezium as kafka upstream data source

src/main/java/org/apache/doris/kafka/connector/utils/FileNameUtils.java, src/main/java/org/apache/doris/kafka/connector/writer/LabelGenerator.java, src/main/java/org/apache/doris/kafka/connector/writer/StreamLoadWriter.java, src/test/java/org/apache/doris/kafka/connector/writer/TestStreamLoadWriter.java
Since the doris stream load label length limit cannot exceed 128 characters.
Although the new version of doris can configure the label length by itself https://github.com/apache/doris/pull/33745, the old version of doris will still be subject to this restriction.
For this reason, we optimized the label generation mechanism and reduced unnecessary parameters. Theoretically, at least 21 unnecessary characters can be reduced.
=> [Improve]Improve the length of generated stream load label

src/main/java/org/apache/doris/kafka/connector/converter/RecordService.java, src/main/java/org/apache/doris/kafka/connector/converter/type/AbstractType.java, src/main/java/org/apache/doris/kafka/connector/converter/type/connect/ConnectDateType.java, src/main/java/org/apache/doris/kafka/connector/converter/type/connect/ConnectTimeType.java, src/main/java/org/apache/doris/kafka/connector/converter/type/connect/ConnectTimestampType.java, src/main/java/org/apache/doris/kafka/connector/converter/type/debezium/DateType.java, src/main/java/org/apache/doris/kafka/connector/converter/type/debezium/MicroTimeType.java, src/main/java/org/apache/doris/kafka/connector/converter/type/debezium/MicroTimestampType.java, src/main/java/org/apache/doris/kafka/connector/converter/type/debezium/NanoTimeType.java, src/main/java/org/apache/doris/kafka/connector/converter/type/debezium/NanoTimestampType.java, src/main/java/org/apache/doris/kafka/connector/converter/type/debezium/TimeType.java, src/main/java/org/apache/doris/kafka/connector/converter/type/util/DateTimeUtils.java, src/main/java/org/apache/doris/kafka/connector/converter/type/util/SchemaUtils.java
Since the `DateTimeUtils` and `SchemaUtils` classes in debezium-connector-jdbc are somewhat different from those in this project, when they are inconsistent, a null pointer exception will occur, so the package reference has been changed.
=> [fix]Fix DateTimeUtils, SchemaUtils referenced packages from debezium-connector-jdbc

src/main/java/org/apache/doris/kafka/connector/cfg/DorisOptions.java, src/main/java/org/apache/doris/kafka/connector/cfg/DorisSinkConnectorConfig.java, src/test/java/org/apache/doris/kafka/connector/converter/TestRecordService.java
Since this parameter is only used when ```converter.mode=debezium_ingestion```, add the debezium prefix to ``schema.evolution`` to become ```debezium.schema.evolution``` to avoid misunderstandings
=> [Improve]schema.evolution adds debezium prefix

pom.xml
You can use the following example to deserialize protobuf data
```
curl -i http://127.0.0.1:8083/connectors -H "Content-Type: application/json" -X POST -d '{ 
"name":"doris-protobuf-test", 
"config":{ 
"connector.class":"org.apache.doris.kafka.connector.DorisSinkConnector", 
"topics":"proto_topic", 
"tasks.max":"1",
"doris.topic2table.map": "proto_topic:proto_tab", 
"buffer.count.records":"100", 
"buffer.flush.time":"10", 
"buffer.size.bytes":"100000", 
"doris.urls":"127.0.0.1", 
"doris.user":"root", 
"doris.password":"", 
"doris.http.port":"8030", 
"doris.query.port":"9030", 
"doris.database":"test", 
"load.model":"stream_load",
"delivery.guarantee":"exactly_once",
"key.converter":"io.confluent.connect.protobuf.ProtobufConverter", …
```
=> [feature]Support reading protobuf serialized data

src/main/java/org/apache/doris/kafka/connector/service/DorisSystemService.java
Since each partition under the topic has a sink task, when the corresponding connector starts, it will connect to doris to determine whether the table exists.
When there are multiple topics, and each topic has multiple partitions, a large number of connections will be made to request doris at the moment of startup, causing the number of connections to exceed the limit.
This PR can reduce a repeated request to determine whether the database exists.
=> [Improve]Optimize to determine whether table in doris exists

src/main/java/org/apache/doris/kafka/connector/metrics/DorisConnectMonitor.java
If ```jmx:false```  is configured, some indicators of jmx are not initialized, resulting NullPointerException.
=> [fix]Fix npe exception caused by closing jmx

.github/workflows/license-eyes.yml, .licenserc.yaml, license-eye-ignore.yml, src/main/java/org/apache/doris/kafka/connector/decode/DorisConverter.java, src/main/java/org/apache/doris/kafka/connector/decode/DorisJsonSchema.java, src/main/java/org/apache/doris/kafka/connector/decode/avro/DorisAvroConverter.java, src/main/java/org/apache/doris/kafka/connector/exception/DataDecodeException.java, src/test/java/org/apache/doris/kafka/connector/decode/avro/DorisAvroConverterTest.java, src/test/resources/decode/avro/product.avsc, src/test/resources/decode/avro/user.avsc
close: https://github.com/apache/doris-kafka-connector/issues/29
Earlier, the file parsing of avro used the `io.confluent.connect.avro.AvroConverter` provided by confluent. This method requires specifying `schema.registry.url` to obtain the schema. Generally speaking, this kind of registration center is provided by confluent. 
At present, it seems that there is some over-reliance on the confluent registration center, so we are open to parsing the schema by reading the avsc file of local avro in order to achieve decoupling from the confluent registration center.
By specifying `value.converter` or  `key.converter` `org.apache.doris.kafka.connector.decode.avro.DorisAvroConverter`.
Configure the parameters of `value.converter.avro.topic2schema.filepath` or …
=> [feature]Implement DorisAvroConverter to support parsing schema from avro avsc file path

src/test/java/org/apache/doris/kafka/connector/writer/TestCopyIntoWriter.java, src/test/java/org/apache/doris/kafka/connector/writer/TestStreamLoadWriter.java
It turns out that the `fetchOffset()` single test of `TestCopyIntoWriter` and `TestStreamLoadWriter` is running. Since jdbc is actually called to obtain the remote offset, the running time of the single test is particularly high.
=> [Improve]Improve the unit test case of DorisWriter

pom.xml
If you encounter this problem when starting doris-kafka-connect.
```
org.apache.kafka.common.config.ConfigException: Topic 'connect-status' supplied via the 'status.storage.topic' property is required to have 'cleanup.policy=compact' to guarantee consistency and durability of connector and task statuses, but found the topic currently has 'cleanup.policy=delete'. Continuing would likely result in eventually losing connector and task statuses and problems restarting this Connect cluster in the future. Change the 'status.storage.topic' property in the Connect worker configurations to use a topic with 'cleanup.policy=compact'.
at org.apache.kafka.connect.util.TopicAdmin.verifyTopicCleanupPolicyOnlyCompact(TopicAdmin.java:581)
at org.apache.kafka.connect.storage.KafkaTopicBasedBackingStore.lamb …
```
=> Update kafka-connect version to 3.7.1

.github/workflows/checkstyle.yaml
Since the code inspection workflow does not specify the Java version, during the actual permission process, it will fail due to the use of a higher version of Java.
```
SEVERE: Step 'removeUnusedImports' found problem in 'src/main/java/org/apache/doris/kafka/connector/decode/avro/DorisAvroConverter.java':
null
java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at com.diffplug.spotless.java.GoogleJavaFormatStep$State.lambda$constructRemoveUnusedFunctio …
```
=> Fix code inspection workflow failure

src/main/java/org/apache/doris/kafka/connector/writer/DorisWriter.java
If the data has been written to doris, the data will no longer be written to avoid repeated consumption. Add logs here to facilitate troubleshooting
=> add log for record offset is smaller than processedOffset

src/main/java/org/apache/doris/kafka/connector/cfg/DorisOptions.java, src/main/java/org/apache/doris/kafka/connector/cfg/DorisSinkConnectorConfig.java, src/main/java/org/apache/doris/kafka/connector/service/DorisDefaultSinkService.java, src/main/java/org/apache/doris/kafka/connector/writer/CopyIntoWriter.java, src/main/java/org/apache/doris/kafka/connector/writer/DorisWriter.java, src/main/java/org/apache/doris/kafka/connector/writer/StreamLoadWriter.java, src/main/java/org/apache/doris/kafka/connector/writer/load/DorisStreamLoad.java, src/test/java/org/apache/doris/kafka/connector/e2e/sink/stringconverter/StringMsgE2ETest.java, src/test/java/org/apache/doris/kafka/connector/service/TestDorisSinkService.java, src/test/java/org/apache/doris/kafka/connector/writer/TestCopyIntoWriter.java, src/test/java/org/apache/doris/kafka/connector/writer/TestStreamLoadWriter.java, src/test/resources/e2e/string_converter/table_field_config.json, src/test/resources/e2e/string_converter/table_field_config1.sql, src/test/resources/e2e/string_converter/table_field_config2.sql
By configuring `'record.tablename.field'`, where the field value is used as the table name to be written, if the data in the topic does not contain this field or the field value is null or empty, the default configured 'doris.topic2table.map' will still be used.  If the mapped table cannot be obtained, the topic will be used as the table.
for example:
```
{
"name": "doris-json-test",
"config": {
"buffer.count.records": "10000",
"buffer.flush.time": "120",
"buffer.size.bytes": "10000000",
"connector.class": "org.apache.doris.kafka.connector.DorisSinkConnector",
"doris.database": "test",
"doris.http.port": "8030",
"doris.password": "",
"doris.query.port": "9030",
"record.tablename.field": "table_name",
"doris.topic2table.map": "json_topic:json_table",
"doris.urls": "127.0.0.1", …
```
=> [improve] Support writing data from one topic to multiple tables.

src/main/java/org/apache/doris/kafka/connector/service/DorisDefaultSinkService.java, src/test/java/org/apache/doris/kafka/connector/service/TestDorisSinkService.java
In the function of https://github.com/apache/doris-kafka-connector/pull/58 supporting one topic to multiple tables, only the data types converted using the `org.apache.kafka.connect.json.JsonConverter` converter are supported. For the converter of `org.apache.kafka.connect.storage.StringConverter`, Currently it is not supported. 
This pr will support records of string type.
=> [improve]support string type record in one topic to multiple tables

src/main/java/org/apache/doris/kafka/connector/converter/RecordService.java
The thrown exception can better indicate which table has made the schema change.
```
org.apache.doris.kafka.connector.exception.SchemaChangeException: Cannot alter table org.apache.doris.kafka.connector.model.TableDescriptor@67cd8027 because schema evolution is disabled
at org.apache.doris.kafka.connector.converter.RecordService.alterTableIfNeeded(RecordService.java:186)
at org.apache.doris.kafka.connector.converter.RecordService.checkAndApplyTableChangesIfNeeded(RecordService.java:150)
at org.apache.doris.kafka.connector.converter.RecordService.processStructRecord(RecordService.java:100)
at org.apache.doris.kafka.connector.converter.RecordService.getProcessedRecord(RecordService.java:305)
at org.apache.doris.kafka.connector.writer.DorisWriter.putBuffer(DorisWriter.java:155)
at …
```
=> [Enhancement]Schema change error prompts the table name

src/main/java/org/apache/doris/kafka/connector/DorisSinkTask.java, src/main/java/org/apache/doris/kafka/connector/cfg/DorisOptions.java, src/main/java/org/apache/doris/kafka/connector/cfg/DorisSinkConnectorConfig.java, src/main/java/org/apache/doris/kafka/connector/model/RespContent.java, src/main/java/org/apache/doris/kafka/connector/utils/ConfigCheckUtils.java, src/main/java/org/apache/doris/kafka/connector/writer/DorisWriter.java, src/main/java/org/apache/doris/kafka/connector/writer/load/DorisStreamLoad.java, src/test/java/org/apache/doris/kafka/connector/cfg/TestDorisSinkConnectorConfig.java, src/test/java/org/apache/doris/kafka/connector/e2e/doris/DorisContainerServiceImpl.java, src/test/java/org/apache/doris/kafka/connector/e2e/sink/AbstractKafka2DorisSink.java, src/test/java/org/apache/doris/kafka/connector/e2e/sink/stringconverter/DorisSinkFailoverSinkTest.java, src/test/resources/docker/doris/be.conf, src/test/resources/docker/doris/fe.conf, src/test/resources/e2e/string_converter/string_msg_failover_connector.json, src/test/resources/e2e/string_converter/string_msg_tab_failover.sql
Currently, after the streamload fails to write, the kafka connect task will stop and can only be started by curl api.
We can explicitly throw RetryException to let the kafka connect framework automatically retry.
At the same time, set the retry interval and time to control the failure strategy.
"max.retries": "10",
"retry.interval.ms": "3000",
=> [Improve] add retry strategy

src/main/java/org/apache/doris/kafka/connector/DorisSinkTask.java, src/main/java/org/apache/doris/kafka/connector/service/DorisDefaultSinkService.java, src/main/java/org/apache/doris/kafka/connector/service/DorisSinkServiceFactory.java, src/test/java/org/apache/doris/kafka/connector/e2e/kafka/KafkaContainerService.java, src/test/java/org/apache/doris/kafka/connector/e2e/kafka/KafkaContainerServiceImpl.java, src/test/java/org/apache/doris/kafka/connector/e2e/sink/stringconverter/StringMsgE2ETest.java, src/test/java/org/apache/doris/kafka/connector/service/TestDorisSinkService.java, src/test/resources/e2e/transforms/regex_router_transforms.json, src/test/resources/e2e/transforms/regex_router_transforms.sql
Currentlly, if using `io.confluent.connect.transforms.ExtractTopic` or `org.apache.kafka.connect.transforms.RegexRouter` or other transforms that mutate topic, **`doris-kafka-connector` will not successfully submit the consumer offset.** because in `org.apache.kafka.connect.sink.SinkTask#preCommit`, the topic corresponds to the original topic before applying any transformations. If the connector is restarted, it will be consumed repeatedly. 
More seriously, by default, **`two_phase_commit` is enabled, data will not be written to doris** because transactions were not successfully committed in `org.apache.kafka.connect.sink.SinkTask#preCommit`. But at this point, both the connector and task are in a normal RUNNING state, and the user is not aware of this abnormal situation. 
So, I think it …
=> [Improve] check topic mutating SMTs

src/main/java/org/apache/doris/kafka/connector/DorisSinkTask.java, src/main/java/org/apache/doris/kafka/connector/cfg/DorisOptions.java, src/main/java/org/apache/doris/kafka/connector/cfg/DorisSinkConnectorConfig.java, src/main/java/org/apache/doris/kafka/connector/service/DorisCombinedSinkService.java, src/main/java/org/apache/doris/kafka/connector/service/DorisDefaultSinkService.java, src/main/java/org/apache/doris/kafka/connector/service/DorisSinkServiceFactory.java, src/main/java/org/apache/doris/kafka/connector/utils/ConfigCheckUtils.java, src/main/java/org/apache/doris/kafka/connector/writer/DorisWriter.java, src/test/java/org/apache/doris/kafka/connector/e2e/sink/stringconverter/StringMsgE2ETest.java, src/test/resources/e2e/string_converter/combine_flush_connector.json, src/test/resources/e2e/string_converter/combine_flush_connector_2pc.json, src/test/resources/e2e/string_converter/combine_flush_tab.sql, src/test/resources/e2e/string_converter/combine_flush_tab_2pc.sql
Currently, during the write process, data is written based on partitions, and the label will be concatenated with the partition ID. This is to ensure exactly-once semantics. However, when there are a large number of partitions, such as 100, even with very small amounts of data, 100 streamload operations will be initiated each time. 
For unique tables, idempotency can be leveraged to achieve exactly-once semantics, so during the write process, all partitions can be merged together for writing.
The configuration is set to  enable.combine.flush=true .​
=> [improve] update config default value and add combine flush mode

src/main/java/org/apache/doris/kafka/connector/model/doris/Field.java, src/main/java/org/apache/doris/kafka/connector/model/doris/Schema.java, src/test/java/org/apache/doris/kafka/connector/converter/TestRecordService.java
When schema_api returns extra columns, deserialization will fail
=> [Fix] ignore schema api response

src/main/java/org/apache/doris/kafka/connector/writer/DorisWriter.java
The change of `processedOffset` should be after the success of streamload, because streamload may fail.
Before the introduction of the retry strategy, if streamload fails, kafka connect will stop directly.
This pr https://github.com/apache/doris-kafka-connector/pull/67 introduces a retry strategy, which will cause `processedOffset` to change during the retry, but streamload will fail
=> [Fix] Fix processedOffset update when retry load
